const Insights = require("../models/insight.model");
const openConnection = require("../db/");
const mongoose = require("mongoose");
const Company = require("./../models/company.model");
const User = require("./../models/user.model");
const bcrypt = require("bcrypt");

const password = "123456";
const hashedPass = bcrypt.hashSync(password, 10);
const users = [
  {
    name: "jl",
    email: "jl@mail.com",
    password: hashedPass,
  },
  {
    name: "Lucie",
    email: "ll@mail.com",
    password: hashedPass,
  },
];

async function seedDatabase() {
  try {
    const db = await openConnection();
    await Company.deleteMany();
    await Insights.deleteMany();
    await User.deleteMany();

    const createdUsers = await User.create(users);

    console.log(`Succesfully connected to ${db.connection.name} database.`);
    const createdCompanies = await Company.create(companies);
    console.log(createdCompanies);
    for (const review of insights) {
      const oneCompany = await Company.findOne({ name: review.company });
      await Insights.create({
        creator: randomUser(createdUsers),
        company: oneCompany._id,
        title: review.title,
        location: review.location,
        compensation: review.compensation,
        date: review.date,
        level: review.level,
        company_xp: review.company_xp,
        total_xp: review.total_xp,
        company_note: review.company_note,
        company_review: review.company_review,
      });
    }
    // const createdInsights = await Insights.create(insights);
    // console.log(`Created ${createdInsights.length} insights 🥸`);
    await mongoose.disconnect();
    console.log(`Succesfully disconnected from ${db.connection.name}`);
  } catch (error) {
    console.error(
      `Something went wrong while creating the seed: ${error.message}`
    );
  }
}

seedDatabase();

function randomUser(array) {
  return array[Math.floor(Math.random() * array.length)]._id;
}
const insights = [
  {
    company: "360Learning",
    title: "Software engineer",
    location: "Remote",
    compensation: 48000,
    date: "2021-07-01",
    level: "Junior",
    company_xp: 0,
    total_xp: 2,
    company_note: 6,
    company_review:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias, dolorum.",
  },
  {
    company: "360Learning",
    title: "Software engineer",
    location: "Remote",
    compensation: 48000,
    date: "2021-07-01",
    level: "Junior",
    company_xp: 0,
    total_xp: 2,
    company_note: 5,
    company_review:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias, dolorum.",
  },
  {
    company: "360Learning",
    title: "Software engineer",
    location: "Remote",
    compensation: 43000,
    date: "2021-02-08",
    level: "Junior",
    company_xp: 0,
    total_xp: 2,
    company_note: 6,
    company_review:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias, dolorum.",
  },
  {
    company: "Sopra Banking Software",
    title: "Software engineer",
    location: "Paris",
    compensation: 75000,
    date: "2022-07-05",
    level: "Senior",
    company_xp: null,
    total_xp: 18,
    company_note: 3,
    company_review:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias, dolorum.",
  },
  {
    company: "360Learning",
    title: "Software engineer",
    location: "Remote",
    compensation: 55000,
    date: "2022-01-01",
    level: "Intermediate",
    company_xp: 1,
    total_xp: 3,
    company_note: 6,
    company_review:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias, dolorum.",
  },
  {
    company: "Descartes Underwriting",
    title: "Software engineer Scientific Engine (Python)",
    location: "Paris",
    compensation: 46000,
    date: "2022-08-25",
    level: "Intermediate",
    company_xp: 0,
    total_xp: 0,
    company_note: 9,
    company_review:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias, dolorum.",
  },
  {
    company: "Microsoft",
    title: "Software engineer",
    location: "Remote",
    compensation: 101000,
    date: "2021-04-15",
    level: "Senior",
    company_xp: 2,
    total_xp: 12,
    company_note: 6,
    company_review:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias, dolorum.",
  },
  {
    company: "AWS",
    title: "Software developement engineer",
    location: "Paris",
    compensation: 60000,
    date: "2023-02-11",
    level: "Intermediate",
    company_xp: 0,
    total_xp: 2,
    company_note: 5,
    company_review:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias, dolorum.",
  },
  {
    company: "Algolia",
    title: "Backend Software Engineer",
    location: "Paris",
    compensation: 65000,
    date: "2022-09-14",
    level: "Senior",
    company_xp: 0,
    total_xp: 5,
    company_note: 7,
    company_review:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias, dolorum.",
  },
  {
    company: "Sogilis",
    title: "Software engineer",
    location: "Grenoble",
    compensation: 40600,
    date: "2022-08-30",
    level: "Senior",
    company_xp: 2,
    total_xp: 8,
    company_note: 4,
    company_review:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias, dolorum.",
  },
  {
    company: "DIMO Software",
    title: "Dev Java",
    location: "Bidart",
    compensation: 34800,
    date: "2022-09-19",
    level: "Junior",
    company_xp: 2,
    total_xp: 2,
    company_note: 6,
    company_review:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias, dolorum.",
  },
  {
    company: "SQUAD",
    title: "Ingénieur DevOps",
    location: "Paris",
    compensation: 50000,
    date: "2023-02-18",
    level: "Intermediate",
    company_xp: 1,
    total_xp: 2,
    company_note: 7,
    company_review:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias, dolorum.",
  },
  {
    company: "Association 42",
    title: "Administrateur système",
    location: "Paris",
    compensation: 35000,
    date: "2022-09-22",
    level: "Junior",
    company_xp: null,
    total_xp: 0,
    company_note: 6,
    company_review:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias, dolorum.",
  },
  {
    company: "Economie d'Energie",
    title: "Chef de projet IT ",
    location: "Paris",
    compensation: 40000,
    date: "2023-02-13",
    level: "Junior",
    company_xp: 3,
    total_xp: 3,
    company_note: 6,
    company_review:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias, dolorum.",
  },
  {
    company: "Tech Innovations",
    title: "Software Engineer",
    location: "San Francisco",
    compensation: 100000,
    date: "2023-03-01",
    level: "Senior",
    company_xp: 5,
    total_xp: 8,
    company_note: 9,
    company_review: "Awesome company with smart people.",
  },
  {
    company: "Tech Innovations",
    title: "Software Engineer",
    location: "San Francisco",
    compensation: 100000,
    date: "2023-03-01",
    level: "Senior",
    company_xp: 5,
    total_xp: 8,
    company_note: 9,
    company_review: "Awesome company with smart people.",
  },
  {
    company: "Data Analytics Inc.",
    title: "Data Analyst",
    location: "New York",
    compensation: 75000,
    date: "2023-02-15",
    level: "Intermediate",
    company_xp: 3,
    total_xp: 4,
    company_note: 8,
    company_review: "Great place to work and learn new skills.",
  },
  {
    company: "Web Development Co.",
    title: "Front-End Developer",
    location: "London",
    compensation: 60000,
    date: "2023-04-01",
    level: "Junior",
    company_xp: 1,
    total_xp: 2,
    company_note: 7,
    company_review: "Good environment and exciting projects.",
  },
  {
    company: "AI Solutions Ltd.",
    title: "AI Researcher",
    location: "Tokyo",
    compensation: 120000,
    date: "2023-02-28",
    level: "Senior",
    company_xp: 10,
    total_xp: 15,
    company_note: 10,
    company_review: "One of the best companies to work for in the field.",
  },
  {
    company: "IT Services Co.",
    title: "IT Support Specialist",
    location: "Paris",
    compensation: 45000,
    date: "2023-03-15",
    level: "Junior",
    company_xp: 1,
    total_xp: 1,
    company_note: 6,
    company_review: "Decent company with nice coworkers.",
  },
  {
    company: "Social Media Co.",
    title: "Social Media Manager",
    location: "Los Angeles",
    compensation: 80000,
    date: "2023-02-01",
    level: "Intermediate",
    company_xp: 4,
    total_xp: 6,
    company_note: 8,
    company_review: "Exciting work and great company culture.",
  },
  {
    company: "E-Commerce Solutions",
    title: "Full-Stack Developer",
    location: "Berlin",
    compensation: 70000,
    date: "2023-04-02",
    level: "Intermediate",
    company_xp: 3,
    total_xp: 5,
    company_note: 7,
    company_review: "Interesting projects and friendly colleagues.",
  },
  {
    company: "Cloud Computing Corp.",
    title: "Cloud Engineer",
    location: "Seattle",
    compensation: 90000,
    date: "2023-03-15",
    level: "Senior",
    company_xp: 6,
    total_xp: 9,
    company_note: 9,
    company_review: "Great company with a strong focus on innovation.",
  },
  {
    company: "Digital Marketing Agency",
    title: "SEO Specialist",
    location: "Sydney",
    compensation: 60000,
    date: "2023-04-01",
    level: "Junior",
    company_xp: 1,
    total_xp: 2,
    company_note: 7,
    company_review: "Great company to start your career in digital marketing.",
  },
  {
    company: "Cybersecurity Co.",
    title: "Cybersecurity Analyst",
    location: "Dubai",
    compensation: 90000,
    date: "2023-03-01",
    level: "Intermediate",
    company_xp: 4,
    total_xp: 6,
    company_note: 9,
    company_review: "Top-notch security company with smart people.",
  },
  {
    company: "Blockchain Solutions",
    title: "Blockchain Developer",
    location: "Hong Kong",
    compensation: 110000,
    date: "2023-04-01",
    level: "Senior",
    company_xp: 7,
    total_xp: 10,
    company_note: 9,
    company_review:
      "Great company with exciting projects in the blockchain space.",
  },
  {
    company: "Healthcare Tech Inc.",
    title: "Healthcare Data Analyst",
    location: "Chicago",
    compensation: 80000,
    date: "2023-02-28",
    level: "Intermediate",
    company_xp: 3,
    total_xp: 5,
    company_note: 8,
    company_review: "Exciting projects in healthcare and great team members.",
  },
  {
    company: "Artificial Intelligence Corp.",
    title: "Machine Learning Engineer",
    location: "Mumbai",
    compensation: 95000,
    date: "2023-03-15",
    level: "Senior",
    company_xp: 5,
    total_xp: 8,
    company_note: 9,
    company_review: "Amazing company culture and brilliant minds.",
  },
  {
    company: "Web Hosting Solutions",
    title: "DevOps Engineer",
    location: "Dublin",
    compensation: 85000,
    date: "2023-02-15",
    level: "Senior",
    company_xp: 3,
    total_xp: 5,
    company_note: 8,
    company_review:
      "Awesome company with a great team and challenging projects.",
  },
  {
    company: "Software Testing Co.",
    title: "Software Tester",
    location: "São Paulo",
    compensation: 50000,
    date: "2023-04-02",
    level: "Junior",
    company_xp: 1,
    total_xp: 1,
    company_note: 7,
    company_review: "Good company for entry-level testers.",
  },
  {
    company: "Marketing Analytics Ltd.",
    title: "Marketing Data Scientist",
    location: "Barcelona",
    compensation: 90000,
    date: "2023-03-15",
    level: "Senior",
    company_xp: 6,
    total_xp: 9,
    company_note: 9,
    company_review: "Great company with talented data scientists and analysts.",
  },
  {
    company: "Social Network Co.",
    title: "Backend Developer",
    location: "Amsterdam",
    compensation: 75000,
    date: "2023-02-01",
    level: "Senior",
    company_xp: 4,
    total_xp: 6,
    company_note: 8,
    company_review: "Great atmosphere and stimulating work.",
  },
  {
    company: "Mobile Gaming Co.",
    title: "Unity Game Developer",
    location: "Los Angeles",
    compensation: 100000,
    date: "2023-04-01",
    level: "Senior",
    company_xp: 5,
    total_xp: 8,
    company_note: 9,
    company_review: "Innovative and exciting mobile games, great team members.",
  },
  {
    company: "Cloud Computing Co.",
    title: "Cloud Solutions Architect",
    location: "New York",
    compensation: 120000,
    date: "2023-03-15",
    level: "Senior",
    company_xp: 8,
    total_xp: 12,
    company_note: 10,
    company_review: "Excellent company with cutting-edge cloud solutions.",
  },
  {
    company: "E-commerce Solutions Inc.",
    title: "Frontend Developer",
    location: "Toronto",
    compensation: 75000,
    date: "2023-02-15",
    level: "Junior",
    company_xp: 1,
    total_xp: 1,
    company_note: 7,
    company_review: "Good company to start your career in e-commerce.",
  },
  {
    company: "Artificial Intelligence Co.",
    title: "AI Research Scientist",
    location: "Tokyo",
    compensation: 150000,
    date: "2023-03-01",
    level: "Senior",
    company_xp: 10,
    total_xp: 15,
    company_note: 10,
    company_review: "Exceptional company with the smartest AI scientists.",
  },
  {
    company: "Web Development Agency",
    title: "Full Stack Developer",
    location: "London",
    compensation: 85000,
    date: "2023-04-02",
    level: "Intermediate",
    company_xp: 4,
    total_xp: 6,
    company_note: 8,
    company_review: "Awesome company to work for, great team and projects.",
  },
  {
    company: "Virtual Reality Co.",
    title: "VR Game Developer",
    location: "Seattle",
    compensation: 100000,
    date: "2023-03-15",
    level: "Intermediate",
    company_xp: 3,
    total_xp: 5,
    company_note: 8,
    company_review:
      "Exciting projects and cutting-edge technology in VR gaming.",
  },
  {
    company: "Digital Advertising Co.",
    title: "Digital Advertising Specialist",
    location: "Paris",
    compensation: 70000,
    date: "2023-03-01",
    level: "Intermediate",
    company_xp: 3,
    total_xp: 5,
    company_note: 7,
    company_review:
      "Great company to develop your skills in digital advertising.",
  },
  {
    company: "Financial Technology Inc.",
    title: "Financial Software Engineer",
    location: "San Francisco",
    compensation: 120000,
    date: "2023-02-01",
    level: "Senior",
    company_xp: 6,
    total_xp: 9,
    company_note: 9,
    company_review:
      "Fantastic company culture and talented software engineers.",
  },
  {
    company: "Blockchain Solutions Co.",
    title: "Blockchain Developer",
    location: "Vancouver",
    compensation: 110000,
    date: "2023-04-01",
    level: "Intermediate",
    company_xp: 4,
    total_xp: 7,
    company_note: 8,
    company_review:
      "Exciting company with a great team working on cutting-edge blockchain solutions.",
  },
  {
    company: "Social Media Co.",
    title: "Social Media Manager",
    location: "Sydney",
    compensation: 80000,
    date: "2023-03-01",
    level: "Intermediate",
    company_xp: 3,
    total_xp: 6,
    company_note: 7,
    company_review:
      "Good company for social media professionals to advance their career.",
  },
  {
    company: "Art and Design Co.",
    title: "Graphic Designer",
    location: "Los Angeles",
    compensation: 65000,
    date: "2023-02-15",
    level: "Junior",
    company_xp: 1,
    total_xp: 1,
    company_note: 7,
    company_review:
      "Great company for designers to build their portfolio and gain experience.",
  },
  {
    company: "Healthcare Software Co.",
    title: "Healthcare Software Developer",
    location: "Chicago",
    compensation: 90000,
    date: "2023-03-15",
    level: "Intermediate",
    company_xp: 3,
    total_xp: 5,
    company_note: 8,
    company_review:
      "Innovative company working on important healthcare software solutions.",
  },
  {
    company: "EdTech Co.",
    title: "Frontend Developer",
    location: "San Francisco",
    compensation: 95000,
    date: "2023-02-01",
    level: "Intermediate",
    company_xp: 2,
    total_xp: 4,
    company_note: 7,
    company_review: "Good company for developers interested in EdTech.",
  },
  {
    company: "Video Conferencing Co.",
    title: "Backend Engineer",
    location: "London",
    compensation: 110000,
    date: "2023-04-02",
    level: "Senior",
    company_xp: 7,
    total_xp: 10,
    company_note: 9,
    company_review:
      "Great company to work for with talented engineers and exciting projects.",
  },
  {
    company: "Cybersecurity Co.",
    title: "Security Analyst",
    location: "New York",
    compensation: 100000,
    date: "2023-02-13",
    level: "Intermediate",
    company_xp: 4,
    total_xp: 6,
    company_note: 8,
    company_review:
      "Cutting-edge cybersecurity company with a focus on innovation and security.",
  },
  {
    company: "Gaming Co.",
    title: "Game Designer",
    location: "Los Angeles",
    compensation: 75000,
    date: "2023-03-01",
    level: "Junior",
    company_xp: 1,
    total_xp: 1,
    company_note: 7,
    company_review:
      "Exciting company to start your career in the gaming industry.",
  },
];
const companies = [...new Set(insights.map((x) => x.company))].map((name) => ({
  name,
}));
console.log(companies);
